name: npm-tag

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Published version to tag'
        required: true
      tag:
        description: 'Tag'
        required: false
        default: 'next'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org

      - name: Add dist-tag
        run: npm dist-tag add ${{ github.event.inputs.version }} ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
